[project]
name = "devops-interview"
version = "0.1.0"
description = "Obsidian notes for DevOps interview"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.50",
    "mkdocs-obsidian-bridge>=1.2.0",
]
